; PlatformIO — ESP32 Barrier Controller
; OLED SSD1306 + 4x IR spots + 1x IR barrier safety + SG90 servo + MQTT

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM3
monitor_port = COM3
lib_deps =
	knolleary/PubSubClient @ ^2.8
	madhephaestus/ESP32Servo @ ^3.0.5
	bblanchon/ArduinoJson @ ^7.3
	adafruit/Adafruit SSD1306 @ ^2.5.7
	adafruit/Adafruit GFX Library @ ^1.11.5
build_flags =
	-I include
	-std=gnu++17
build_unflags = -std=gnu++11
